-- 코드를 입력하세요
# SELECT * FROM USED_GOODS_BOARD;
# SELECT * FROM USED_GOODS_REPLY;

SELECT 
    (SELECT TITLE 
     FROM USED_GOODS_BOARD 
     WHERE BOARD_ID = R.BOARD_ID AND 
           DATE_FORMAT(CREATED_DATE, '%Y-%m') = '2022-10') AS TITLE,
    R.BOARD_ID,
    R.REPLY_ID,
    R.WRITER_ID,
    R.CONTENTS,
    DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE  -- 수정된 부분
FROM 
    USED_GOODS_REPLY R
WHERE
    (SELECT TITLE 
     FROM USED_GOODS_BOARD 
     WHERE BOARD_ID = R.BOARD_ID AND 
           DATE_FORMAT(CREATED_DATE, '%Y-%m') = '2022-10') IS NOT NULL
ORDER BY 
    R.CREATED_DATE ASC, TITLE ASC;